### PR TITLE
FIX Undefined cache when multiple tokens are waiting

### LINKED ISSUE #316: Error 503 in pep when many tokens are requested simultaneously
log line shows the following

time=2016-05-31T06:57:34.696Z | lvl=ERROR | corr=3fc5b86a-dce3-481f-8ab8-568d77d818ab | trans=3fc5b86a-dce3-481f-8ab8-568d77d818ab | op=/v1/updateContext | msg=[VALIDATION-GEN-003] Error connecting to Keystone authentication: KEYSTONE_AUTHENTICATION_ERROR: There was a connection error while authenticating to Keystone: 503

It happens when many tokens are requested simultaneously

### PR DESCRIPTION
**Pull request by dmoranj**
Fixes #316

### CODE REVIEW

**Comment by AlvaroVega** [comment]
LGTM

File: lib/services/cacheUtils.js [hunk 1]
```diff
@@ -91,10 +97,18 @@ function createDomainEnabledCacheHandler(domain, processValueFn, cache, cacheTyp
 function cacheAndHold(cache, cacheType, cacheKey, retrieveRequestFn, processValueFn, callback) {
     var cachedValue = cache.data[cacheType].get(cacheKey);
 
+    function getCacheEventId() {
+        return cacheType + ':' + cacheKey;
+    }
+
     if (cachedValue[cacheKey]) {
```
Comment (gtorodelvalle) [inline lib/services/cacheUtils.js]: I see there are no controls on the existence of `cachedValue`. Just wanted to cross-check with you that it will always exist.

File: lib/services/cacheUtils.js [hunk 2]
```diff
@@ -91,10 +97,18 @@ function createDomainEnabledCacheHandler(domain, processValueFn, cache, cacheTyp
...
+        logger.debug('Value found in the cache [%s] for key [%s]: %s', cacheType, cacheKey, cachedValue[cacheKey]);
+
         processValueFn(cachedValue[cacheKey], callback);
-    } else if (cache.updating[cacheType]) {
-        cache.channel.on(cacheType,
+    } else if (cache.updating[cacheType][cacheKey]) {
```
Comment (gtorodelvalle) [inline lib/services/cacheUtils.js]: I see there are no controls on the existence of `cache.updating[cacheType]`. Just wanted to cross-check with you that it will always exist to avoid uncontrolled `ReferenceError`s.

Comment (dmoranj) [inline lib/services/cacheUtils.js]: It will always exist, as it is created with the three types of caches in the first place, as you can see in the declarations at the top of the module.

File: lib/services/cacheUtils.js (hunk 1 above)
Comment (dmoranj) [inline lib/services/cacheUtils.js]: It seems weird but yes, it will. The "get()" function of a nodeCache cache returns an empty object if the key does not exist, so cachedValue will always be an object.

Comment (gtorodelvalle) [inline lib/services/cacheUtils.js]: NTC

File: lib/services/cacheUtils.js (hunk 2 above)
Comment (gtorodelvalle) [inline lib/services/cacheUtils.js]: NTC
